require 'solidus_core'
require 'deface'
require 'solidus_recently_viewed/configuration'
require 'solidus_recently_viewed/engine'
require 'solidus_recently_viewed/version'
require 'coffee_script'
require 'sass/rails'
